// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 The TrovePass contributors
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { BRAND } from './src/brand.js';
import { nextVersion } from './tools/fastlane.mjs';
import { stripSource, stripJsSource, lostCode } from './tools/comments.mjs';

const run = promisify(execFile);

const ROOT = import.meta.dirname;
const SRC = path.join(ROOT, 'src');
const OUT_DIR = path.join(ROOT, 'dist');
const WEB_DIR = path.join(ROOT, 'web');
const PAYLOAD_DIR = path.join(OUT_DIR, 'www');

if (!BRAND || !BRAND.name || !BRAND.slug) {
console.error('build: src/brand.js must export a name and a slug');
process.exit(1);
}
if (/YOUR_HANDLE|YOUR-DOMAIN|<handle>|<domain>/i.test(String(BRAND.appId || ''))) {
console.log(`build: WARNING — the application id is still the placeholder ${BRAND.appId}`);
console.log('build:           set it in src/brand.js before any release (see docs/DEVELOPING.md)');
}

const OUT = path.join(OUT_DIR, `${BRAND.slug}.js`);

const ORDER = ['brand.js', 'version.js', 'core.js', 'fingerprint.js'];

function bumpPatch() {
const p = path.join(SRC, 'version.js');
let text = fs.readFileSync(p, 'utf8');
const re = /const SPW_VERSION = '(\d+\.\d+\.\d+)';/;
const m = re.exec(text);
if (!m) {
console.error('bump: SPW_VERSION not found');
process.exit(1);
}
const next = nextVersion(m[1]);
fs.writeFileSync(p, text.replace(re, `const SPW_VERSION = '${next}';`));
console.log(`bump: version ${m[1]} -> ${next}`);
return next;
}

function readAll() {
const parts = [];
for (const rel of ORDER) {
const p = path.join(SRC, rel);
if (!fs.existsSync(p)) {
console.error(`MISSING src file: ${rel}`);
process.exit(1);
}
parts.push(fs.readFileSync(p, 'utf8').replace(/\n$/, ''));
}
return parts.join('\n\n');
}

const version = bumpPatch();
const body = readAll();

const stripped = stripJsSource(body);
const lost = lostCode(body, stripped);
if (lost.length) {
console.error(`build: the comment strip lost ${lost.length} line(s) of CODE (${lost.slice(0, 8).join(', ')}${lost.length > 8 ? ', …' : ''})`);
console.error('build: that is a bug in tools/comments.mjs — no artifact was written');
process.exit(1);
}

const banner = `// ${BRAND.name} ${version} — generated by build.mjs, do not edit\n// SPDX-License-Identifier: GPL-3.0-or-later\n// SPDX-FileCopyrightText: 2026 The TrovePass contributors\n`;

fs.mkdirSync(OUT_DIR, { recursive: true });
const built = banner + stripped.text + '\n';
fs.writeFileSync(OUT, built);

const deflate = (text) => zlib.deflateSync(Buffer.from(text)).length;
const payload = { files: 0, raw: 0, stripped: 0, gzip: 0, gzipStripped: 0 };
fs.rmSync(PAYLOAD_DIR, { recursive: true, force: true });
fs.mkdirSync(path.join(PAYLOAD_DIR, 'web'), { recursive: true });
fs.mkdirSync(path.join(PAYLOAD_DIR, 'dist'), { recursive: true });
for (const name of fs.readdirSync(WEB_DIR).sort()) {
const bytes = fs.readFileSync(path.join(WEB_DIR, name));
const text = bytes.toString('utf8');
const result = stripSource(name, text);
const lostWeb = lostCode(text, result);
if (lostWeb.length) {
console.error(`build: the comment strip lost ${lostWeb.length} line(s) of CODE in web/${name} (${lostWeb.slice(0, 8).join(', ')})`);
console.error('build: that is a bug in tools/comments.mjs — no artifact was written');
process.exit(1);
}
fs.writeFileSync(path.join(PAYLOAD_DIR, 'web', name), result.text === text ? bytes : Buffer.from(result.text));
payload.files += 1;
payload.raw += bytes.length;
payload.stripped += Buffer.byteLength(result.text);
payload.gzip += deflate(text);
payload.gzipStripped += deflate(result.text);
}
fs.writeFileSync(path.join(PAYLOAD_DIR, 'dist', `${BRAND.slug}.js`), built);

const shipped = [
{ label: `dist/${BRAND.slug}.js`, abs: OUT },
...fs.readdirSync(WEB_DIR).filter((f) => f.endsWith('.js')).map((f) => ({ label: `dist/www/web/${f}`, abs: path.join(PAYLOAD_DIR, 'web', f) })),
];
const parsed = await Promise.all(shipped.map(async ({ label, abs }) => {
try {
await run(process.execPath, ['--check', abs]);
return null;
} catch (e) {
return `${label}: ${String(e.stderr || e.message).trim().split('\n')[0]}`;
}
}));
const broken = parsed.filter(Boolean);
if (broken.length) {
console.error('SYNTAX ERROR:\n' + broken.join('\n'));
process.exit(1);
}

const stats = fs.statSync(OUT);
const saved = ((1 - payload.stripped / payload.raw) * 100).toFixed(0);
console.log(`built dist/${BRAND.slug}.js — ${built.split('\n').length} lines, ${stats.size} bytes, version ${version}`);
console.log(`built dist/www/ — ${payload.files} files, ${payload.raw} → ${payload.stripped} bytes (-${saved}%), deflate ${payload.gzip} → ${payload.gzipStripped} (-${payload.gzip - payload.gzipStripped})`);
console.log(`syntax: OK (${shipped.length} shipped JavaScript files parsed)`);
