// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 The TrovePass contributors
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { BRAND } from '../src/brand.js';
import { SPW_VERSION } from '../src/version.js';
import { stripFor, withoutJavaComments } from './comments.mjs';
import { LOCALES, DEFAULT_LOCALE } from '../web/i18n.js';

const ROOT = path.resolve(import.meta.dirname, '..');
const ANDROID = path.join(ROOT, 'android');
const ASSETS_DIR = path.join(ANDROID, 'app/src/main/assets/www');
const MANIFEST = path.join(ANDROID, 'app/src/main/AndroidManifest.xml');
const APP_GRADLE = path.join(ANDROID, 'app/build.gradle');
const WEB_DIR = path.join(ROOT, 'web');
const BUNDLE = path.join(ROOT, 'dist', `${BRAND.slug}.js`);

const TEXTY = /\.(js|mjs|css|html|svg|json|webmanifest|txt)$/;
const sourceText = (rel, src) => (TEXTY.test(rel) ? stripFor(rel, fs.readFileSync(src, 'utf8')) : null);
const STAMPS = [
[/^\/\/ .*? \d+\.\d+\.\d+ — generated by build\.mjs/m, '// banner #.#.# — generated by build.mjs'],
[/const SPW_VERSION = '\d+\.\d+\.\d+';/, "const SPW_VERSION = '#.#.#';"],
];
const withoutVersionStamp = (text) => STAMPS.reduce((acc, [re, to]) => acc.replace(re, to), text);
const versionStamps = (text) => {
const found = STAMPS.map(([re]) => ((re.exec(text) || [])[0] || '').match(/\d+\.\d+\.\d+/));
return [...new Set(found.filter(Boolean).map((m) => m[0]))];
};

function assetPlan() {
const plan = new Map();
for (const name of fs.readdirSync(WEB_DIR)) {
const src = path.join(WEB_DIR, name);
if (fs.statSync(src).isFile()) plan.set(`web/${name}`, { src, optional: false });
}
plan.set(`dist/${BRAND.slug}.js`, { src: BUNDLE, optional: true });
return plan;
}

function walk(dir, prefix = '') {
const out = [];
for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
if (entry.isDirectory()) out.push(...walk(path.join(dir, entry.name), rel));
else out.push(rel);
}
return out;
}

const GENERATED = /(^|\/)(build|\.gradle|\.cxx|local\.properties)(\/|$)/;
const sources = (rels) => rels.filter((rel) => !GENERATED.test(rel));

const withoutXmlComments = (text) => text.replace(/<!--[\s\S]*?-->/g, '');


function xmlCommentProblems(text, label) {
const problems = [];
for (const match of text.matchAll(/<!--([\s\S]*?)-->/g)) {
if (match[1].includes('--')) {
const snippet = match[1].trim().replace(/\s+/g, ' ').slice(0, 80);
problems.push(`${label}: an XML comment contains a double hyphen (AAPT2 rejects it) — "${snippet}…"`);
}
}
return problems;
}

function xmlBalanceProblems(text, label) {
const problems = [];
const body = withoutXmlComments(text).replace(/<\?[\s\S]*?\?>/g, '');
const stack = [];
const tagRe = /<(\/?)([A-Za-z_][\w.:-]*)((?:"[^"]*"|[^>"'"]|'[^']*')*?)(\/?)>/g;
let match;
let lastIndex = 0;
while ((match = tagRe.exec(body)) !== null) {
if (body.slice(lastIndex, match.index).includes('<')) problems.push(`${label}: stray "<"`);
lastIndex = tagRe.lastIndex;
const closing = match[1] === '/';
const name = match[2];
const selfClosing = match[4] === '/';
if (selfClosing) continue;
if (closing) {
const open = stack.pop();
if (open !== name) problems.push(`${label}: </${name}> closes <${open === undefined ? 'nothing' : open}>`);
} else {
stack.push(name);
}
}
if (stack.length) problems.push(`${label}: unclosed <${stack[stack.length - 1]}>`);
return problems;
}

function localeConfigText() {
const tags = Object.keys(LOCALES);
if (tags.length === 0) return null;
const header = '<?xml version="1.0" encoding="utf-8"?>\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">';
return header + '\n' + tags.map((t) => `    <locale android:name="${t}"/>`).join('\n') + '\n</locale-config>\n';
}

function writeLocaleConfig() {
const text = localeConfigText();
if (text === null) throw new Error('android-sync: could not read the app\'s languages out of web/i18n.js');
const file = path.join(ANDROID, 'app/src/main/res/xml/locales_config.xml');
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, text);
return file;
}

export function checkAndroid() {
const problems = [];
const notes = [];
if (!fs.existsSync(ANDROID)) {
problems.push('no android/ directory');
return { problems, notes };
}

const plan = assetPlan();
for (const [rel, { src, optional }] of plan) {
const dest = path.join(ASSETS_DIR, rel);
if (!fs.existsSync(src)) {
if (optional) notes.push(`skipped dist/ comparison (no bundle yet — run npm run build)`);
else problems.push(`missing source for asset ${rel}: ${path.relative(ROOT, src)}`);
continue;
}
if (!fs.existsSync(dest)) {
problems.push(`asset missing: ${rel} (run node tools/android-sync.mjs --write)`);
continue;
}
if (rel.startsWith('dist/')) {
const srcText = fs.readFileSync(src, 'utf8');
const destText = fs.readFileSync(dest, 'utf8');
if (withoutVersionStamp(srcText) !== withoutVersionStamp(destText)) {
problems.push(`asset out of date: ${rel} (run node tools/android-sync.mjs --write)`);
} else {
const behind = versionStamps(destText).filter((v) => v !== SPW_VERSION);
if (behind.length) {
notes.push(
`bundle asset is stamped ${behind.join(', ')} while the build is ${SPW_VERSION} — run node tools/android-sync.mjs --write before a release`
);
}
}
} else {
const stripped = sourceText(rel, src);
const same = stripped === null
? fs.readFileSync(src).equals(fs.readFileSync(dest))
: stripped === fs.readFileSync(dest, 'utf8');
if (!same) problems.push(`asset out of date: ${rel} (run node tools/android-sync.mjs --write)`);
}
}
if (fs.existsSync(ASSETS_DIR)) {
for (const rel of walk(ASSETS_DIR)) {
if (!plan.has(rel)) problems.push(`stale asset with no source: ${rel}`);
}
}

for (const rel of walk(ASSETS_DIR)) {
if (!plan.has(rel)) problems.push(`stale asset: ${rel} (no source for it — run node tools/android-sync.mjs --write)`);
}

const gradle = fs.readFileSync(APP_GRADLE, 'utf8');
const declared = (/applicationId\s+'([^']+)'/.exec(gradle) || [])[1] || '';
if (!declared) {
problems.push('app/build.gradle declares no applicationId');
} else if (declared !== BRAND.appId) {
problems.push(`android applicationId "${declared}" disagrees with src/brand.js "${BRAND.appId}"`);
}

const NETWORK_PERMISSIONS = [
'android.permission.INTERNET',
'android.permission.ACCESS_NETWORK_STATE',
'android.permission.ACCESS_WIFI_STATE',
'android.permission.CHANGE_NETWORK_STATE',
'android.permission.CHANGE_WIFI_STATE',
];
const manifest = withoutXmlComments(fs.readFileSync(MANIFEST, 'utf8'));
const permissions = [...manifest.matchAll(/<uses-permission\b[^>]*android:name="([^"]+)"/g)].map((m) => m[1]);
if (permissions.length) {
problems.push(
`AndroidManifest declares ${permissions.join(', ')} — this app asks for NO permission at all, and "cannot exfiltrate anything" is its whole pitch`
);
}
const networked = permissions.filter((p) => NETWORK_PERMISSIONS.includes(p));
if (networked.length) {
problems.push(`AndroidManifest declares ${networked.join(', ')} — this app cannot exfiltrate anything, which is its whole pitch`);
}
const namedPermissions = [...new Set([...manifest.matchAll(/android\.permission\.([A-Z_]+)/g)].map((m) => `android.permission.${m[1]}`))];
if (namedPermissions.length) {
problems.push(`AndroidManifest names ${namedPermissions.join(', ')} — the shell holds and names no permission at all`);
}
if (!/android:allowBackup="false"/.test(manifest)) {
problems.push('AndroidManifest must set allowBackup="false" so the saved entries are not swept into a backup');
}
if (!/android:usesCleartextTraffic="false"/.test(manifest)) {
problems.push('AndroidManifest must set usesCleartextTraffic="false"');
}
{
const configRel = 'app/src/main/res/xml/locales_config.xml';
const configFile = path.join(ANDROID, configRel);
const expected = localeConfigText();
if (!/android:localeConfig="@xml\/locales_config"/.test(manifest)) {
problems.push('AndroidManifest must reference @xml/locales_config so Android 13+ can offer the app its own languages');
} else if (expected === null) {
problems.push("could not read the app's languages out of web/i18n.js — has the VALUES table been restructured?");
} else if (!fs.existsSync(configFile)) {
problems.push(`missing ${configRel}, which the manifest references (the per-app language list) — run node tools/android-sync.mjs --write`);
} else if (fs.readFileSync(configFile, 'utf8') !== expected) {
problems.push(`${configRel} does not match the app's own languages, in their order — run node tools/android-sync.mjs --write`);
}
}
const extractionRel = 'app/src/main/res/xml/data_extraction_rules.xml';
const extractionFile = path.join(ANDROID, extractionRel);
if (!/android:dataExtractionRules="@xml\/data_extraction_rules"/.test(manifest)) {
problems.push('AndroidManifest must reference @xml/data_extraction_rules so Android 12+ backs nothing up');
} else if (!fs.existsSync(extractionFile)) {
problems.push(`missing ${extractionRel}, which the manifest references (the API 31+ backup rules)`);
} else {
const rules = withoutXmlComments(fs.readFileSync(extractionFile, 'utf8'));
for (const half of ['cloud-backup', 'device-transfer']) {
if (!new RegExp(`<${half}\\b[\\s\\S]*?<exclude\\b`).test(rules)) {
problems.push(`${extractionRel} excludes nothing under <${half}>: nothing must be backed up`);
}
}
}
const configChanges = (/android:configChanges="([^"]*)"/.exec(manifest) || [])[1] || '';
const handled = configChanges.split('|').filter(Boolean);
const required = ['orientation', 'screenSize', 'keyboardHidden', 'fontScale', 'uiMode', 'locale', 'density'];
const missing = required.filter((entry) => !handled.includes(entry));
if (missing.length) {
problems.push(
`android:configChanges is missing ${missing.join(', ')} — an unlisted change RECREATES the Activity: the page reloads, what was typed is lost, and a credential prompt up at the time asks twice and closes the app`
);
}

const javaFiles = walk(path.join(ANDROID, 'app/src/main/java')).map((rel) =>
path.join(ANDROID, 'app/src/main/java', rel)
);
const java = withoutJavaComments(javaFiles.map((f) => fs.readFileSync(f, 'utf8')).join('\n'));
const networkApi = /\b(OkHttpClient|HttpURLConnection|URLConnection|java\.net\.|InetAddress|ServerSocket|SocketChannel|\bSocket\b|WebSocket)\b/.exec(java);
if (networkApi) problems.push(`Android source uses a network API: ${networkApi[0]}`);
if (!/FLAG_SECURE/.test(java)) problems.push('MainActivity must set FLAG_SECURE on the window');
if (/FilteredWebView/.test(java)) {
problems.push('the long-press menu must NOT be filtered: that wrapper hid every entry it could not recognise, and an unrecognised one may be the keyboard\'s own Clipboard item');
}
if (!/new WebView\(this\)/.test(java)) {
problems.push('MainActivity must build a plain WebView(this) — the engine\'s menu is left as Chromium built it');
}
const navRefusals = [...java.matchAll(/shouldOverrideUrlLoading\s*\(\s*WebView\s+\w+\s*,\s*(WebResourceRequest|String)\s+\w+\s*\)\s*\{\s*return\s+true\s*;/g)].map((m) => m[1]);
for (const [signature, why] of [
['WebResourceRequest', 'API 24+ asks this one'],
['String', 'API 21–23 asks only this one, and the platform default there is to NAVIGATE'],
]) {
if (!navRefusals.includes(signature)) {
problems.push(`MainActivity does not refuse navigation in shouldOverrideUrlLoading(WebView, ${signature}) — ${why}`);
}
}
if (/getExtras\(\)\s*\./.test(java)) {
problems.push('a chained call on ClipDescription.getExtras(): it is null until setExtras() is called, and that NPE killed the app on a phone when Copy was pressed');
}
if (!/setExtras\(/.test(java)) problems.push('the sensitive-clip extras are never set, so EXTRA_IS_SENSITIVE can never be applied');

{
const shortcutsFile = path.join(ANDROID, 'app/src/main/res/xml/shortcuts.xml');
if (!/android\.app\.shortcuts/.test(manifest)) {
problems.push('AndroidManifest does not reference @xml/shortcuts — the launcher menu would be empty');
} else if (!fs.existsSync(shortcutsFile)) {
problems.push('missing app/src/main/res/xml/shortcuts.xml, which the manifest references');
} else {
const xml = withoutXmlComments(fs.readFileSync(shortcutsFile, 'utf8'));
const appJs = fs.readFileSync(path.join(ROOT, 'web/app.js'), 'utf8');
const tabs = ((appJs.match(/const TABS = \[([^\]]*)\]/) || [])[1] || '')
.split(',')
.map((t) => t.trim().replace(/^'|'$/g, ''))
.filter(Boolean);
const targets = [...xml.matchAll(/android:targetPackage="([^"]+)"/g)].map((m) => m[1]);
const values = [...xml.matchAll(/<extra android:name="dev\.trovepass\.extra\.TAB" android:value="([^"]+)"/g)].map((m) => m[1]);
const labels = [...xml.matchAll(/android:shortcutShortLabel="@string\/([^"]+)"/g)].map((m) => m[1]);
if (tabs.length === 0) {
problems.push('could not read the page\'s tab list out of web/app.js — has `const TABS` moved?');
} else {
for (const value of values) {
if (!tabs.includes(value)) problems.push(`a launcher shortcut names tab "${value}", which the page does not have (${tabs.join(', ')})`);
}
const wanted = values.map((v) => `shortcut_${v}`);
if (labels.join(',') !== wanted.join(',')) {
problems.push(`the launcher shortcuts' labels (${labels.join(', ') || 'none'}) do not line up with the sections they open (${wanted.join(', ')})`);
}
}
for (const target of targets) {
if (target !== BRAND.appId) problems.push(`a launcher shortcut targets "${target}" rather than the application id "${BRAND.appId}" — a rename would leave dead intents`);
}
const strings = withoutXmlComments(fs.readFileSync(path.join(ANDROID, 'app/src/main/res/values/strings.xml'), 'utf8'));
const english = LOCALES[DEFAULT_LOCALE] || {};
for (const value of values) {
const word = typeof english[`tab.${value}`] === 'string' ? english[`tab.${value}`].trim() : null;
const declared = (strings.match(new RegExp(`<string name="shortcut_${value}">([^<]*)</string>`)) || [])[1];
if (word === null) problems.push(`the page's English has no tab.${value}, so the launcher's word for it cannot be checked`);
else if (declared !== word) {
problems.push(`the launcher's "${value}" shortcut says "${declared}" while the tab it opens says "${word}" — one place, one word`);
}
}
}
}
const moduleGradle = fs.readFileSync(path.join(ANDROID, 'app/build.gradle'), 'utf8');
const targetSdk = Number((/^\s*targetSdk\s+(\d+)/m.exec(moduleGradle) || [])[1]);
const compileSdk = Number((/^\s*compileSdk\s+(\d+)/m.exec(moduleGradle) || [])[1]);
if (!(compileSdk >= targetSdk)) {
problems.push(`compileSdk ${compileSdk} is below targetSdk ${targetSdk}: AAPT2 and the platform APIs reject that`);
}
if (targetSdk >= 35) {
for (const [re, why] of [
[/setDecorFitsSystemWindows\(false\)/, 'the window is still asked to fit the system bars'],
[/WindowInsets\.Type\.systemBars\(\)/, 'the system-bar insets are never read'],
[/WindowInsets\.Type\.displayCutout\(\)/, 'the display-cutout inset is never read: a notch or a hole-punch is NOT part of systemBars(), so the app can be crowded against the camera on those phones'],
[/WindowInsets\.Type\.ime\(\)/, 'the keyboard inset is never read, so the keyboard can cover the password field'],
[/setPadding\(/, 'the insets are read but never applied'],
[/insets: top=/, 'the shell does not report the padding it applied, which is what tools/android-emulator.mjs reads on a device (the padding is the one effect no source check can see)'],
[/onPageCommitVisible/, 'the shell does not report when the page commits a first frame, which is what tells the pixel check whether there is a page to measure at all'],
]) {
if (!re.test(java)) problems.push(`targetSdk ${targetSdk} enforces edge-to-edge, but ${why}`);
}
if (!/windowSoftInputMode="adjustResize"/.test(manifest)) {
problems.push('the keyboard inset needs android:windowSoftInputMode="adjustResize" on the activity');
}
if (!/new FrameLayout\(this\)/.test(java) || !/setContentView\((?!webView\))/.test(java)) {
problems.push(
'the window insets are not spent on a container: padding the WebView itself leaves the page\'s viewport at the full screen height, so everything pinned to the bottom of the page — the toast bar, the last row of a panel — sits behind the navigation bar'
);
}
}

for (const rel of sources(walk(ANDROID)).filter((r) => r.endsWith('.xml'))) {
const text = fs.readFileSync(path.join(ANDROID, rel), 'utf8');
problems.push(...xmlBalanceProblems(text, rel));
problems.push(...xmlCommentProblems(text, rel));
}

for (const density of ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']) {
for (const name of ['ic_launcher', 'ic_launcher_round']) {
const rel = `app/src/main/res/mipmap-${density}/${name}.png`;
if (!fs.existsSync(path.join(ANDROID, rel))) problems.push(`missing launcher icon: ${rel} (run npm run icons:gen)`);
}
}
const manifestText = fs.readFileSync(MANIFEST, 'utf8');
if (/android:icon="@drawable\//.test(manifestText)) {
problems.push('the manifest points the launcher icon at a drawable: launchers cannot render a vector, use the mipmaps');
}
if (!/android:icon="@mipmap\/ic_launcher"/.test(manifestText)) problems.push('the manifest does not reference @mipmap/ic_launcher');
if (!/android:roundIcon="@mipmap\/ic_launcher_round"/.test(manifestText)) problems.push('the manifest does not reference @mipmap/ic_launcher_round');
for (const rel of ['app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml', 'app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml']) {
const file = path.join(ANDROID, rel);
if (!fs.existsSync(file)) {
problems.push(`missing adaptive icon: ${rel}`);
continue;
}
const text = fs.readFileSync(file, 'utf8');
if (!/foreground android:drawable="@drawable\/ic_launcher_foreground"/.test(text)) {
problems.push(`${rel} does not use @drawable/ic_launcher_foreground`);
}
if (!/background android:drawable="@color\/trovepass_icon_bg"/.test(text)) {
problems.push(`${rel} does not declare @color/trovepass_icon_bg as its background: the plate must be full-bleed and OUR colour, not the launcher's and not absent`);
}
}

const resValues = path.join(ANDROID, 'app/src/main/res/values/colors.xml');
const colorsXml = withoutXmlComments(fs.readFileSync(resValues, 'utf8'));
const namedColor = (name) => {
const hex = new RegExp(`<color\\s+name="${name}"[^>]*>\\s*#([0-9a-fA-F]{6,8})\\s*</color>`).exec(colorsXml);
return hex ? '#' + hex[1].slice(-6).toLowerCase() : '';
};
const css = fs.readFileSync(path.join(ROOT, 'web', 'style.css'), 'utf8');
const darkBg = (/:root\s*\{[\s\S]*?--bg:\s*(#[0-9a-f]{6})/i.exec(css) || [])[1];
const accent = (/:root\s*\{[\s\S]*?--acc:\s*(#[0-9a-f]{6})/i.exec(css) || [])[1];
const lightBlock = (/\:root\[data-scheme="light"\]\s*\{([\s\S]*?)\n\}/.exec(css) || [])[1] || '';
const lightBg = (/--bg:\s*(#[0-9a-f]{6})/i.exec(lightBlock) || [])[1];
const iconBg = (/:root\s*\{[\s\S]*?--icon-bg:\s*(#[0-9a-f]{6})/i.exec(css) || [])[1];
const shellPlate = namedColor('trovepass_icon_bg');
const shellAccent = namedColor('trovepass_accent');
if (!darkBg || !accent || !lightBg || !iconBg) {
problems.push('web/style.css declares no --bg/--icon-bg/--acc token to check the Android chrome and the icon plate against');
} else {
if (shellPlate !== iconBg.toLowerCase()) {
problems.push(
`android trovepass_icon_bg is ${shellPlate || 'missing'} but the stylesheet's --icon-bg is ${iconBg} — the launcher tile and the maskable web twin would be two different colours`
);
}
if (shellAccent !== accent.toLowerCase()) {
problems.push(`android trovepass_accent is ${shellAccent || 'missing'} but the stylesheet's --acc is ${accent}`);
}
const dayChrome = namedColor('trovepass_chrome_day');
const nightChrome = namedColor('trovepass_chrome_night');
if (dayChrome !== lightBg.toLowerCase() || nightChrome !== darkBg.toLowerCase()) {
problems.push(
`android chrome colours are day=${dayChrome || 'missing'}/night=${nightChrome || 'missing'} but the app's own backgrounds are light ${lightBg} / dark ${darkBg}`
);
}
const nightValues = path.join(ANDROID, 'app/src/main/res/values-night/colors.xml');
const dayAlias = /<color\s+name="trovepass_chrome"\s*>\s*@color\/trovepass_chrome_day\s*</.test(colorsXml);
const nightAlias = fs.existsSync(nightValues)
? /<color\s+name="trovepass_chrome"\s*>\s*@color\/trovepass_chrome_night\s*</.test(
withoutXmlComments(fs.readFileSync(nightValues, 'utf8'))
)
: false;
if (!dayAlias || !nightAlias) {
problems.push('the theme\u2019s chrome colour is not pointed at the scheme\u2019s own colour in values/ and values-night/');
}
const boolOf = (rel) => {
const file = path.join(ANDROID, 'app/src/main/res', rel);
return fs.existsSync(file) ? (/<bool\s+name="trovepass_light_bars"\s*>\s*(true|false)\s*</.exec(fs.readFileSync(file, 'utf8')) || [])[1] : '';
};
const dayBars = boolOf('values/bools.xml');
const nightBars = boolOf('values-night/bools.xml');
if (dayBars !== 'true' || nightBars !== 'false') {
problems.push(`the bar-icon flag is day=${dayBars || 'missing'}/night=${nightBars || 'missing'} \u2014 a light scheme needs dark icons on its bars, and the dark scheme needs light ones`);
}
}
const vectorFile = path.join(ANDROID, 'app/src/main/res/drawable/ic_launcher.xml');
const webIconFile = path.join(ROOT, 'web', 'icon.svg');
const readColors = (file, re) =>
new Set([...fs.readFileSync(file, 'utf8').matchAll(re)].map((m) => '#' + m[1].slice(-6).toLowerCase()));
const vectorColors = readColors(vectorFile, /android:fillColor="#([0-9a-fA-F]{6,8})"/g);
const iconColors = readColors(webIconFile, /fill="#([0-9a-fA-F]{6})"/g);
const colourMismatch =
[...iconColors].some((c) => !vectorColors.has(c)) || [...vectorColors].some((c) => !iconColors.has(c));
if (colourMismatch) {
problems.push(
`the launcher vector and web/icon.svg disagree on the palette: vector has ${[...vectorColors].sort().join(' ')}, icon has ${[...iconColors].sort().join(' ')}`
);
}
const normalise = (d) => d.replace(/[\s,]+/g, '');
const isPlate = (d) => /^M0,?0[hH]108[vV]108[hH]-108[zZ]$/.test(d);
const subpathsOf = (text, re) =>
[...text.matchAll(re)]
.flatMap((m) => m[1].split(/(?=[Mm])/))
.map(normalise)
.filter((d) => d && !isPlate(d));
const vectorPaths = subpathsOf(fs.readFileSync(vectorFile, 'utf8'), /android:pathData="([^"]+)"/g);
const iconPaths = subpathsOf(fs.readFileSync(webIconFile, 'utf8'), /<path[^>]*\sd="([^"]+)"/g);
if (vectorPaths.join(' ') !== iconPaths.join(' ')) {
problems.push(
`the launcher vector and web/icon.svg disagree on the artwork: vector has [${vectorPaths.join(' ')}], icon has [${iconPaths.join(' ')}] — the same paths are drawn in both files by hand, so an icon change has to touch both (and then npm run icons:gen)`
);
}

return { problems, notes };
}

function writeAssets() {
const written = [];
const planKeys = new Set(assetPlan().keys());
for (const [rel, { src, optional }] of assetPlan()) {
if (!fs.existsSync(src)) {
if (optional) continue;
throw new Error(`android-sync: missing source ${path.relative(ROOT, src)}`);
}
const dest = path.join(ASSETS_DIR, rel);
fs.mkdirSync(path.dirname(dest), { recursive: true });
const stripped = sourceText(rel, src);
if (stripped === null) fs.copyFileSync(src, dest);
else fs.writeFileSync(dest, stripped);
written.push(rel);
}
for (const rel of walk(ASSETS_DIR)) {
if (!planKeys.has(rel)) {
fs.rmSync(path.join(ASSETS_DIR, rel));
written.push(`-${rel}`);
}
}
return written;
}

function main(argv) {
if (argv.includes('--write')) {
const written = writeAssets();
for (const rel of written) console.log(`wrote android/app/src/main/assets/www/${rel}`);
console.log(`wrote ${path.relative(ROOT, writeLocaleConfig())}`);
const { problems, notes } = checkAndroid();
for (const n of notes) console.log(`note: ${n}`);
for (const p of problems) console.error(`android-sync: ${p}`);
return problems.length ? 1 : 0;
}
const { problems, notes } = checkAndroid();
for (const n of notes) console.log(`note: ${n}`);
if (problems.length) {
for (const p of problems) console.error(`android-sync: ${p}`);
console.error(`\nandroid-sync: ${problems.length} problem(s).`);
return 1;
}
console.log('android-sync: shell in step — assets match, app id agrees, no permission named, no network API');
return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
process.exit(main(process.argv.slice(2)));
}
