plugins {
    id 'com.android.application'
}

android {

    namespace 'dev.trovepass'

    compileSdk 36

    defaultConfig {

        applicationId 'io.github.u_20240816.trovepass'

        minSdk 21
        targetSdk 36

        versionCode 10000
        versionName '1.0.0'
    }

    buildTypes {

        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
